version: "3.8"

services:
  # fastapi:
  #   build: .
  #   container_name: smart_search_api
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - meilisearch
  #     - redis
  #   environment:
  #     - MEILI_HOST=http://meilisearch:7700
  #     - REDIS_HOST=redis
  #   volumes:
  #     - .:/app

  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - meilisearch
  #     - redis
  #   environment:
  #     - MEILI_HOST=http://meilisearch:7700
  #     - REDIS_HOST=redis

  #   volumes:
  #     - ./backend:/app
  # backend:
  #   build: ./backend
  #   container_name: backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - meilisearch
  #     - redis
  #   environment:
  #     - MEILISEARCH_HOST=http://meilisearch:7700
  #     # - REDIS_HOST=redis
  fastapi:
    build: .
    container_name: smart_search_api
    ports:
      - "8000:8000"
    depends_on:
      - meilisearch
      - redis
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - REDIS_HOST=redis
    volumes:
      - .:/app

  meilisearch:
    image: getmeili/meilisearch:v1.4
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=YN6_9abs_f_HkWC1Fva2XlortnmOmPWvIGqiqjTEVAM
    volumes:
      - meili_data:/meili_data

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend

volumes:
  meili_data:
